### ISSUE TITLE
RHEL 7.7 - check if minimum release needs to be installed - ERROR

### ISSUE THREAD

**Issue by pafra** [mk-ansible-roles/sap-hana-preconfigure#11]

**Comment by pafra** [comment]
Hi,

i have on a fresh installed RHEL 7.7 this erro

TASK [mk-ansible-roles.sap_hana_preconfigure : check if minimum release needs to be installed] ***************************************************************************************************************************************
fatal: [sapsbdhdb11]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: . Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}

thx
franz

**Comment by berndfinger** [comment]
solved upstream in https://github.com/linux-system-roles/sap-hana-preconfigure/pull/26 .
